### ISSUE TITLE
no proxy url if pointing to self

### ISSUE THREAD

**Issue by stevenvachon** [Rob--W/proxy-from-env#5]
```js
process.env.HTTP_PROXY = "http://proxy/";
getProxyFromUrl("http://proxy/");
//-> http://proxy/
```

I think that it should return `undefined`, since a proxy to the same proxy is redundant.

**Comment by Rob--W** [comment]
I agree that proxying an already-proxied URL is somewhat redundant, but I'm not going to add a special case for the situation because the requests are similar but not strictly equivalent. For example, the proxy might have a different DNS record for the referenced host name (compared to the resolved host name as seen by the client).
